### ISSUE TITLE
⚡️ web assembly

### ISSUE THREAD

**Issue by tanhauhau** [react-knowledgeable/talks#24]
I want to learn about web assembly, so I force myself to learn by having to prepare a talk.

who are you and where to find you
---

I'm Tan Li Hau, currently front-end developer at Shopee.
You can find me from lihautan.com, twitter.com/lihautan, github.com/tanhauhau

intro of the talk
---

planner
---
- I prefer to give this talk at: https://github.com/react-knowledgeable/react-knowledgeable-talks/issues/20

- Number of minutes needed to ⚡️: 🤷, I'll strive to do a 10 minute.

**Comment by wgao19** [comment]
github issue can't validate content but a description / intro of the talk is required, and plz also provide a more respectful estimate of time, closing because we don't want other people to follow suite

if you've learned about web assembly and have found something interesting to share, plz submit again

suggestions for re-submission:
- include a description of the talk
- please consider taking on a personal and insightful perspective, prefer not to have an "intro to X" type of talk
