### ISSUE TITLE
🐈 Intro to Netlify for React Developers

### ISSUE THREAD

**Issue by swyxio** [react-knowledgeable/talks#29]
who are you and where to find you

swyx, @swyx
---

intro of the talk
---

Intro to Netlify with demos of advanced features with RK's site.

resources
---
- video  
  https://engineers.sg/v/3830

planner
---
- I prefer to give this talk at: react-knowledgeable/events#5
- Number of minutes needed to ⚡️: 30

**Edit** by @wgao19 - reference issue transferred to the events repo

**Comment by swyxio** [comment]
given that the meetup is jamstack focused, i might do a different talk or a shorter talk. up to u all

**Comment by thchia** [comment]
@sw-yx we are trying to keep the talks lightning format, which means under 10mins 😅. Perhaps something netlify related?

As it coincides with the launch of JAMstack Singapore, we will do some intro-to-JAMstack style talks so perhaps looking at tooling like netlify might work on that theme (I know it’s rather more basic than your usual style tho).

**Comment by wgao19** [comment]
hey 👋 @sw-yx 

lets’s keep it simple, both react and jamstack topics are fine, make sure it’s lightning ⚡️ and plz talk about whichever you feel like the most / most interesting

**Comment by swyxio** [comment]
😂ok but i’m  happy to do a full talk next time

i’ll do an intro to netlify for react devs then. 10 mins

**Comment by wgao19** [comment]
hey @sw-yx cool let's talk about Netlify :D  

In the mean time, _no hard sell_ but we offer to make your talk more connected with us because we use Netlify in [our community site](https://reactknowledgeable.org/)
- u can say we're exploiting netlify preview because some of our bad developers (like myself) just code and test on preview XD
- we're also saving our tokens in Netlify
- @thchia is building our rsvp using airtable + netlify functions
- maybe you can even develop your talk around what our site can do to make use of Netlify better ([repo here](https://github.com/react-knowledgeable/rk-community-site/), PR welcome too)

**Comment by swyxio** [comment]
ok

**Comment by wgao19** [comment]
Follow up: We'll have this talk _Concurrent React from Scratch_ at the internal RK podium of Shopee on **Friday Nov 29, 6pm**, [link to issue here](https://github.com/Shopee/shopee-react-knowledgeable/issues/161). For those of you who are interested to attend: please [DM us on Twitter](https://twitter.com/reknowledgeable/) or [comment on the event issue](https://github.com/Shopee/shopee-react-knowledgeable/issues/161) so we know to check you in.

Referencing Shopee/shopee-react-knowledgeable#161

**Edit:**

Resource links for this talk  
https://github.com/Shopee/shopee-react-knowledgeable/issues/161#issuecomment-559864107

**Comment by wgao19** [comment]
hey @sw-yx  thank you for the talk! 

will close this issue now, if you have slides / links to share, feel free to update the content and it will be picked up by our website in the next release
