### ISSUE TITLE
⚡️ Code splitting 101

### ISSUE THREAD

**Issue by nah611** [react-knowledgeable/talks#35]
who are you and where to find you
---
An Ha Nguyen (Web FE Order team)

intro of the talk
---

Quick sharing/recap on code splitting in Web FE: how does it work, pros/cons and some thoughts on splitting React components effectively while maintaining high UX.

<details>
  <summary>planner</summary>

- I prefer to give this talk at: Can discuss later, currently I'm not certain about my schedule next month.
- Number of minutes needed to ⚡️: 15-20? (still planning)
- [x] I am happy to have this talk recorded by @engineersftw (by default, we record talks to be accessible by more audience, if you don't want, please uncheck this)

</details>

**Comment by wgao19** [comment]
Hi An Ha thanks for the proposal! Looks like this is proposing to the internal podium at Shopee is it? I apologize for the confusion but please go ahead create an issue in [this repo](https://github.com/Shopee/shopee-react-knowledgeable/issues). I cannot transfer this issue neither because it does not belong to the same organization.

Regarding time, we don't have to hurry to deliver this. Although I suggest that we start working on this talk recently, we can schedule some casual chats with @KenLSM for some brainstorms, what do you think?

**Comment by nah611** [comment]
sure, I'll move it. I have some rough contents to share. Still in process of organizing/researching more of my talk
